

/// 在线转化工具 https://javiercbk.github.io/json_to_dart/
class Autogenerated {
  List<LvList> lvList;
  int result;
  List<Data> data;

  Autogenerated({this.lvList, this.result, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['lvList'] != null) {
      lvList = new List<LvList>();
      json['lvList'].forEach((v) {
        lvList.add(new LvList.fromJson(v));
      });
    }
    result = json['result'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.lvList != null) {
      data['lvList'] = this.lvList.map((v) => v.toJson()).toList();
    }
    data['result'] = this.result;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class LvList {
  String romaBg;
  int totalStar;
  int id;
  String lvlBg;
  String lvlName;

  LvList({this.romaBg, this.totalStar, this.id, this.lvlBg, this.lvlName});

  LvList.fromJson(Map<String, dynamic> json) {
    romaBg = json['romaBg'];
    totalStar = json['totalStar'];
    id = json['id'];
    lvlBg = json['lvlBg'];
    lvlName = json['lvlName'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['romaBg'] = this.romaBg;
    data['totalStar'] = this.totalStar;
    data['id'] = this.id;
    data['lvlBg'] = this.lvlBg;
    data['lvlName'] = this.lvlName;
    return data;
  }
}

class Data {
  String iuin;
  String roomId;
  String fightLevel;
  String recordTime;
  String killNum;
  String deathNum;
  String assNum;
  String lastScore;
  String rank;
  String heroTypeId;
  String achieveId;
  String nickname;

  Data(
      {this.iuin,
        this.roomId,
        this.fightLevel,
        this.recordTime,
        this.killNum,
        this.deathNum,
        this.assNum,
        this.lastScore,
        this.rank,
        this.heroTypeId,
        this.achieveId,
        this.nickname});

  Data.fromJson(Map<String, dynamic> json) {
    iuin = json['iuin'];
    roomId = json['room_id'];
    fightLevel = json['fight_level'];
    recordTime = json['record_time'];
    killNum = json['kill_num'];
    deathNum = json['death_num'];
    assNum = json['ass_num'];
    lastScore = json['last_score'];
    rank = json['rank'];
    heroTypeId = json['hero_type_id'];
    achieveId = json['achieve_id'];
    nickname = json['nickname'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['iuin'] = this.iuin;
    data['room_id'] = this.roomId;
    data['fight_level'] = this.fightLevel;
    data['record_time'] = this.recordTime;
    data['kill_num'] = this.killNum;
    data['death_num'] = this.deathNum;
    data['ass_num'] = this.assNum;
    data['last_score'] = this.lastScore;
    data['rank'] = this.rank;
    data['hero_type_id'] = this.heroTypeId;
    data['achieve_id'] = this.achieveId;
    data['nickname'] = this.nickname;
    return data;
  }
}
